// ========== PRACTICE PROMPTS ==========
const PROMPTS = {
  speaking1: [
    "Do you agree or disagree: It is better to live in a small town than in a big city. Use specific reasons and examples.",
    "Some people prefer to study alone. Others prefer to study with a group. Which do you prefer and why?",
    "What is the most important quality of a good teacher? Use details and examples to explain.",
    "Do you agree or disagree: People today spend too much time on social media.",
    "If you could change one thing about your hometown, what would it be and why?",
    "Some people prefer to eat at restaurants. Others prefer to prepare food at home. Which do you prefer?",
    "Do you agree or disagree: Technology has made our lives more stressful.",
    "What is the most important invention of the last 100 years? Explain why.",
    "Do you prefer to take risks or play it safe? Give reasons and examples.",
    "Some people think grades encourage learning. Others think grades limit real learning. What's your view?",
    "Do you agree or disagree: Children should be required to help with household chores.",
    "Would you rather have a job with a high salary but long hours, or a lower salary with more free time?",
    "What is the best way to learn about a new culture? Use specific examples.",
    "Do you agree or disagree: University students should be required to attend classes.",
    "Some people prefer to get up early. Others prefer to stay up late. Which do you prefer?",
    "Do you agree or disagree: It's more important to enjoy your job than to earn a lot of money.",
    "What is the most important thing parents can teach their children?",
    "Do you prefer learning from books or from experience? Explain why.",
    "Some people save money for the future. Others spend it immediately. Which is better?",
    "Do you agree or disagree: Playing sports teaches children important life lessons."
  ],
  speaking24: [
    "The university announces it will close the library on weekends to save money. The student disagrees. Summarize the announcement and explain why the student opposes it.",
    "The reading defines 'social loafing' — people putting less effort in groups. The professor gives a workplace example. Explain how the example illustrates the concept.",
    "The professor discusses two strategies companies use to enter new markets. Summarize both using the professor's examples.",
    "The university plans to replace the campus shuttle with a bike-sharing program. The student supports this change. Explain the announcement and the student's reasons.",
    "The reading explains 'anchoring bias' in decision-making. The professor gives a real-estate pricing example. Explain the connection.",
    "The professor explains two types of animal mimicry. Summarize both types with the examples given.",
    "The school newspaper proposes converting the student lounge into a computer lab. The student disagrees. Summarize and explain.",
    "The reading describes 'reciprocity' in social psychology. The professor gives a marketing example. Explain how it demonstrates the concept.",
    "The professor discusses two methods organisms use to survive extreme temperatures. Summarize both with examples."
  ],
  writing2: [
    "Your professor asks: Should universities require all students to take public speaking courses? Student A says yes — communication skills are essential. Student B says no — students should focus on their major. What is your opinion?",
    "Discussion topic: Is it better to have a job you love with low pay, or a job you dislike with high pay? Student A values passion. Student B values financial security. Share your view.",
    "Should governments invest more in space exploration or in solving problems on Earth? Student A supports space exploration. Student B wants to focus on climate and poverty. Share your view.",
    "Should social media companies be responsible for content posted by users? Student A says yes — they have the power. Student B says no — that limits free speech. What do you think?",
    "Is remote work better than working in an office? Student A prefers remote for flexibility. Student B prefers office for collaboration. Join the discussion.",
    "Should college athletes be paid? Student A says yes — they generate revenue. Student B says no — scholarships are enough. Share your opinion.",
    "Is it better to travel to many places briefly or spend a long time in one place? Student A prefers variety. Student B prefers depth. What's your view?",
    "Should schools teach financial literacy as a required course? Student A says yes — it's essential life knowledge. Student B says no — parents should teach this. Your opinion?",
    "Is it better to make decisions quickly or take time to deliberate? Student A values speed. Student B values careful thought. What do you think?",
    "Should AI tools like ChatGPT be allowed in university courses? Student A says yes — it's the future. Student B says no — it undermines learning. Share your view."
  ]
};

// ========== VOCABULARY ==========
const VOCABULARY = [
  { word: "subsequently", def: "after that; happening later", example: "She graduated and subsequently found a job." },
  { word: "nevertheless", def: "despite what was just said; however", example: "The task was difficult; nevertheless, they completed it on time." },
  { word: "albeit", def: "although; even though", example: "He accepted the job, albeit with some reservations." },
  { word: "constraints", def: "limitations or restrictions", example: "Budget constraints forced the team to cut features." },
  { word: "facilitate", def: "to make something easier or possible", example: "Technology facilitates communication across distances." },
  { word: "inherent", def: "existing as a natural part of something", example: "There are inherent risks in any investment." },
  { word: "paradigm", def: "a model or pattern; a way of thinking", example: "The internet created a new paradigm for education." },
  { word: "predominantly", def: "mainly; for the most part", example: "The audience was predominantly young professionals." },
  { word: "implications", def: "possible effects or consequences", example: "The policy has serious implications for small businesses." },
  { word: "empirical", def: "based on observation or experience, not theory", example: "Empirical evidence supports the theory." },
  { word: "comprehensive", def: "including all or nearly all aspects", example: "The report provides a comprehensive analysis." },
  { word: "controversial", def: "causing disagreement or argument", example: "The decision was highly controversial." },
  { word: "phenomenon", def: "a fact or event that can be observed", example: "Climate change is a well-documented phenomenon." },
  { word: "hypothesis", def: "a proposed explanation to be tested", example: "The hypothesis was confirmed by the experiment." },
  { word: "substantial", def: "large in amount or importance", example: "The company made a substantial profit this year." },
  { word: "acquisition", def: "the process of gaining something", example: "Language acquisition begins in early childhood." },
  { word: "adequate", def: "enough; sufficient for a purpose", example: "The salary was barely adequate for living expenses." },
  { word: "ambiguous", def: "having more than one meaning; unclear", example: "The instructions were ambiguous and confusing." },
  { word: "analogous", def: "similar in some way; comparable", example: "The brain is often considered analogous to a computer." },
  { word: "contemporary", def: "belonging to the present time; modern", example: "Contemporary art challenges traditional boundaries." },
  { word: "controversy", def: "prolonged public disagreement", example: "The new law sparked considerable controversy." },
  { word: "diminish", def: "to make or become less", example: "Nothing could diminish her enthusiasm for the project." },
  { word: "elaborate", def: "detailed and complicated; to explain further", example: "Could you elaborate on that point?" },
  { word: "fluctuate", def: "to rise and fall irregularly", example: "Stock prices fluctuate daily." },
  { word: "incorporate", def: "to include as part of something", example: "The design incorporates elements from multiple cultures." },
  { word: "inevitable", def: "certain to happen; unavoidable", example: "Change is inevitable in any growing organization." },
  { word: "innovative", def: "introducing new ideas or methods", example: "The company is known for its innovative products." },
  { word: "offset", def: "to counterbalance or compensate for", example: "Lower costs offset the decline in revenue." },
  { word: "preliminary", def: "happening before a main event; initial", example: "Preliminary results suggest the treatment works." },
  { word: "subtle", def: "not obvious; difficult to notice", example: "There's a subtle difference between the two words." },
  { word: "coherent", def: "logical and well-organized", example: "She presented a coherent argument in her essay." },
  { word: "concurrent", def: "happening at the same time", example: "Two concurrent events caused the power failure." },
  { word: "derive", def: "to get something from a source", example: "Many English words derive from Latin." },
  { word: "distinct", def: "clearly different or separate", example: "The two species have distinct characteristics." },
  { word: "erosion", def: "gradual wearing away; decline", example: "Erosion has shaped these cliffs over millions of years." },
  { word: "exert", def: "to apply force, influence, or effort", example: "Parents exert a strong influence on children." },
  { word: "feasible", def: "possible and practical to do", example: "Is this plan financially feasible?" },
  { word: "hierarchy", def: "a system of ranking; levels of importance", example: "In the corporate hierarchy, she's a director." },
  { word: "impose", def: "to force something on someone", example: "The government imposed new regulations on businesses." },
  { word: "modify", def: "to make partial changes to something", example: "We need to modify our approach to solve this." },
  { word: "notwithstanding", def: "in spite of; despite", example: "Notwithstanding the challenges, they succeeded." },
  { word: "persist", def: "to continue despite difficulty", example: "She persisted with her research for five years." },
  { word: "predominant", def: "most common or most powerful", example: "English is the predominant language in business." },
  { word: "proximity", def: "nearness in distance or time", example: "The proximity of the school to her home was convenient." },
  { word: "rigorous", def: "extremely thorough and careful", example: "The study followed rigorous scientific methods." },
  { word: "scrutiny", def: "careful and critical examination", example: "His work came under intense scrutiny." },
  { word: "simultaneously", def: "at the same time", example: "She managed to work and study simultaneously." },
  { word: "supplement", def: "something added to complete or enhance", example: "He took vitamins to supplement his diet." },
  { word: "thereby", def: "by that means; as a result", example: "He resigned, thereby ending his 20-year career." },
  { word: "undermine", def: "to weaken gradually", example: "Constant criticism can undermine a child's confidence." }
];
