// ========== PERSONALIZED IMPROVEMENT DATA ==========

// Your misspelled words drill
const SPELLING_DRILL = [
  // === YOUR personal errors ===
  { wrong: "managzine", correct: "magazine", hint: "mag-a-ZINE" },
  { wrong: "appretiate", correct: "appreciate", hint: "a-PPRE-ci-ate (double P)" },
  { wrong: "recevied", correct: "received", hint: "re-CEIV-ed (i before e after c)" },
  { wrong: "resposibility", correct: "responsibility", hint: "re-SPON-si-BIL-ity" },
  { wrong: "movitate", correct: "motivate", hint: "MO-ti-vate" },
  { wrong: "hight", correct: "high", hint: "just 4 letters: h-i-g-h" },
  { wrong: "poetries", correct: "poems", hint: "poetry = uncountable, use POEMS" },
  { wrong: "built", correct: "build", hint: "after helps/can/will → use base form: build" },

  // === i before e confusion ===
  { wrong: "recieve", correct: "receive", hint: "i before e EXCEPT after C → reCEIve" },
  { wrong: "beleive", correct: "believe", hint: "beLIEve (there's a LIE inside)" },
  { wrong: "acheive", correct: "achieve", hint: "aCHIEve (i before e)" },
  { wrong: "decieve", correct: "deceive", hint: "after C → EI: deCEIve" },
  { wrong: "percieve", correct: "perceive", hint: "after C → EI: perCEIve" },
  { wrong: "concieve", correct: "conceive", hint: "after C → EI: conCEIve" },
  { wrong: "wierd", correct: "weird", hint: "WEIRD is weird — EI not IE (exception!)" },
  { wrong: "foriegn", correct: "foreign", hint: "FOR-EIGN (e before i — exception)" },
  { wrong: "freind", correct: "friend", hint: "frIEnd (i before e)" },
  { wrong: "theif", correct: "thief", hint: "thIEf (i before e)" },

  // === Double letter traps ===
  { wrong: "accomodate", correct: "accommodate", hint: "2 C's + 2 M's: ac-COM-mo-date" },
  { wrong: "occured", correct: "occurred", hint: "double C + double R: oc-CURR-ed" },
  { wrong: "occassion", correct: "occasion", hint: "2 C's, 1 S: oc-CA-sion" },
  { wrong: "neccessary", correct: "necessary", hint: "1 C, 2 S's: ne-CES-sa-ry" },
  { wrong: "begining", correct: "beginning", hint: "double N: be-GIN-NING" },
  { wrong: "succesful", correct: "successful", hint: "double C + double S: suc-CESS-ful" },
  { wrong: "refered", correct: "referred", hint: "double R: re-FERR-ed" },
  { wrong: "prefered", correct: "preferred", hint: "double R: pre-FERR-ed" },
  { wrong: "recomend", correct: "recommend", hint: "one C, double M: re-COM-MEND" },
  { wrong: "dissapoint", correct: "disappoint", hint: "1 S, 1 P: dis-AP-POINT" },
  { wrong: "embarass", correct: "embarrass", hint: "double R + double S: em-BAR-RASS" },
  { wrong: "harrass", correct: "harass", hint: "one R, double S: ha-RASS" },
  { wrong: "tommorow", correct: "tomorrow", hint: "one M, double R: to-MOR-ROW" },
  { wrong: "writting", correct: "writing", hint: "single T: wri-TING" },
  { wrong: "proffesional", correct: "professional", hint: "one F, double S: pro-FESS-ion-al" },

  // === Silent/hidden letters ===
  { wrong: "enviroment", correct: "environment", hint: "en-vi-RON-ment (hidden N)" },
  { wrong: "goverment", correct: "government", hint: "go-VERN-ment (hidden N)" },
  { wrong: "Wenesday", correct: "Wednesday", hint: "Wed-NES-day (silent D)" },
  { wrong: "Febuary", correct: "February", hint: "Feb-RU-ary (hidden R)" },
  { wrong: "libary", correct: "library", hint: "li-BRAR-y (hidden R)" },
  { wrong: "intresting", correct: "interesting", hint: "in-TER-est-ing (hidden E)" },
  { wrong: "diffrent", correct: "different", hint: "dif-FER-ent (hidden E)" },
  { wrong: "probaly", correct: "probably", hint: "prob-AB-ly (hidden A)" },
  { wrong: "surprize", correct: "surprise", hint: "sur-PRISE (no Z, it's S)" },

  // === -ance vs -ence confusion ===
  { wrong: "independant", correct: "independent", hint: "ends in -ENT not -ANT" },
  { wrong: "existance", correct: "existence", hint: "ends in -ENCE not -ANCE" },
  { wrong: "occurance", correct: "occurrence", hint: "ends in -ENCE: occur-RENCE" },
  { wrong: "maintainance", correct: "maintenance", hint: "main-TEN-ance (this one IS -ance)" },
  { wrong: "attendence", correct: "attendance", hint: "ends in -ANCE: attend-ANCE" },
  { wrong: "confidance", correct: "confidence", hint: "ends in -ENCE: confid-ENCE" },
  { wrong: "referance", correct: "reference", hint: "ends in -ENCE: refer-ENCE" },

  // === Tricky everyday words ===
  { wrong: "seperate", correct: "separate", hint: "there's A RAT in sep-A-R-A-te" },
  { wrong: "definately", correct: "definitely", hint: "de-FINITE-ly (finite is inside)" },
  { wrong: "immediatly", correct: "immediately", hint: "im-MEDI-ATE-ly (ate inside)" },
  { wrong: "unfortunatly", correct: "unfortunately", hint: "un-FOR-tu-NATE-ly" },
  { wrong: "basicly", correct: "basically", hint: "basic + ALLY (not just -ly)" },
  { wrong: "beautifull", correct: "beautiful", hint: "beauti-FUL (one L only)" },
  { wrong: "untill", correct: "until", hint: "one L only: un-TIL" },
  { wrong: "excercise", correct: "exercise", hint: "EX-er-cise (no C before er)" },
  { wrong: "arguement", correct: "argument", hint: "argu-MENT (no E in middle)" },
  { wrong: "judgement", correct: "judgment", hint: "judg-MENT (no E — American English)" },
  { wrong: "knowlege", correct: "knowledge", hint: "KNOW-LEDGE (ledge at end)" },
  { wrong: "strenght", correct: "strength", hint: "STRENG-TH (ng before th)" },
  { wrong: "concious", correct: "conscious", hint: "CON-SCI-OUS (sci inside)" },
  { wrong: "grammer", correct: "grammar", hint: "ends in -AR not -ER" },
  { wrong: "calender", correct: "calendar", hint: "ends in -AR not -ER" },
  { wrong: "pronounciation", correct: "pronunciation", hint: "pro-NUN-ci-ation (no 'ou')" },
  { wrong: "temperture", correct: "temperature", hint: "tem-PER-A-ture (4 syllables)" },

  // === Look-alikes (similar words, different meaning) ===
  { wrong: "affect", correct: "effect", hint: "EFFECT = noun (an effect). AFFECT = verb (to affect someone)" },
  { wrong: "then", correct: "than", hint: "THAN = comparison (bigger than). THEN = time (and then)" },
  { wrong: "there", correct: "their", hint: "THEIR = belongs to them. THERE = a place. THEY'RE = they are" },
  { wrong: "your", correct: "you're", hint: "YOU'RE = you are. YOUR = belongs to you" },
  { wrong: "its", correct: "it's", hint: "IT'S = it is. ITS = belongs to it (no apostrophe)" },
  { wrong: "loose", correct: "lose", hint: "LOSE = opposite of win (one O). LOOSE = not tight (two O's)" },
  { wrong: "quite", correct: "quiet", hint: "QUIET = no noise (qui-ET). QUITE = very/fairly" },
  { wrong: "principle", correct: "principal", hint: "PRINCIPAL = head/main (pal at end). PRINCIPLE = rule/belief" },
  { wrong: "advise", correct: "advice", hint: "ADVICE = noun (give advice). ADVISE = verb (I advise you)" },
    { wrong: "stationary", correct: "stationery", hint: "stationERY = paper/pens (E for envelope). stationARY = not moving" },
  { wrong: "compliment", correct: "complement", hint: "COMPLEMENT = completes. COMPLIMENT = praise" },
  { wrong: "wether", correct: "whether", hint: "WHETHER = if. WEATHER = rain/sun" },

  // === Words people join/split wrong ===
  { wrong: "alot", correct: "a lot", hint: "TWO words: a + lot (always)" },
  { wrong: "infact", correct: "in fact", hint: "TWO words: in + fact" },
  { wrong: "eventhough", correct: "even though", hint: "TWO words: even + though" },
  { wrong: "aswell", correct: "as well", hint: "TWO words: as + well" },
  { wrong: "ofcourse", correct: "of course", hint: "TWO words: of + course" },  
  { wrong: "infront", correct: "in front", hint: "TWO words: in + front" },
  { wrong: "eachother", correct: "each other", hint: "TWO words: each + other" },
  { wrong: "alright", correct: "all right", hint: "TWO words in formal: all + right" },
  { wrong: "everyday", correct: "every day", hint: "EVERY DAY (2 words) = each day. EVERYDAY (1 word) = ordinary" },
  { wrong: "can not", correct: "cannot", hint: "ONE word: cannot (never 'can not' in formal writing)" }
];

// Listen & Repeat sentences (increasing difficulty)
const REPEAT_SENTENCES = [
  // Level 1: Short (5-8 words)
  { text: "The library closes at nine tonight.", level: 1 },
  { text: "Please submit your assignment by Friday.", level: 1 },
  { text: "The professor cancelled tomorrow's lecture.", level: 1 },
  { text: "You can find the bookstore downstairs.", level: 1 },
  { text: "The deadline has been extended until Monday.", level: 1 },
  { text: "All students must attend the orientation.", level: 1 },
  { text: "The cafeteria opens at seven in the morning.", level: 1 },
  { text: "You need to show your ID at the entrance.", level: 1 },
  { text: "The exam will cover chapters three through eight.", level: 1 },
  { text: "Parking is available behind the main building.", level: 1 },
  { text: "The assignment is due at the end of the week.", level: 1 },
  { text: "Please turn off your phone during the lecture.", level: 1 },
  { text: "Registration begins on the first of September.", level: 1 },

  // Level 2: Medium (9-13 words)
  { text: "Students who wish to drop a course must do so by October.", level: 2 },
  { text: "The new science building will be completed by the end of next year.", level: 2 },
  { text: "Bears, wolves, and large cats are located to the right of the entrance.", level: 2 },
  { text: "Please refrain from using your phone during the presentation.", level: 2 },
  { text: "The scholarship is available to students who maintain a high grade point average.", level: 2 },
  { text: "For those with children, we offer summer camps and educational opportunities.", level: 2 },
  { text: "The museum is open every day except Monday and public holidays.", level: 2 },
  { text: "You will need to complete the online registration before attending the workshop.", level: 2 },
  { text: "The professor suggested that we review the first three chapters before the midterm.", level: 2 },
  { text: "All international students are required to submit their documents by the fifteenth.", level: 2 },
  { text: "The research team discovered that the results were consistent with earlier findings.", level: 2 },
  { text: "Free tutoring sessions are available in the learning center every Tuesday and Thursday.", level: 2 },
  { text: "Students who wish to change their major should consult with an academic advisor first.", level: 2 },
  { text: "The visitors center located near the front entrance can give you more information.", level: 2 },

  // Level 3: Long (14-18 words)
  { text: "The university has decided to extend library hours during the final examination period to accommodate students.", level: 3 },
  { text: "Avoid banging or tapping on the displays and enclosures as this may disturb the animals.", level: 3 },
  { text: "Students interested in the summer research program should contact the department office before the deadline.", level: 3 },
  { text: "The committee has approved a proposal to build a new recreation center on the south side of campus.", level: 3 },
  { text: "According to the study, individuals who exercise regularly tend to perform better on cognitive tests than those who do not.", level: 3 },
  { text: "The professor explained that the phenomenon occurs naturally in regions where temperatures drop below freezing for extended periods.", level: 3 },
  { text: "Due to construction near the east entrance, visitors are advised to use the parking lot on the opposite side of the building.", level: 3 },
  { text: "The financial aid office will be holding information sessions throughout the week for students who need assistance with their applications.", level: 3 },
  { text: "Researchers believe that the decline in the bee population is primarily caused by pesticide use and the loss of natural habitats.", level: 3 },
  { text: "The city council voted unanimously to increase funding for public transportation in order to reduce traffic congestion downtown.", level: 3 },
  { text: "The committee recommended that all first-year students be required to attend an orientation session before classes begin.", level: 3 },
  { text: "Recent studies suggest that regular physical exercise can significantly improve academic performance among university students.", level: 3 }
];

// Daily study plan (30-day)
const DAILY_PLAN = [
  { day: 1, focus: "Speaking", task: "Memorize Speaking Task 1 template. Say it out loud 10 times.", time: "15 min" },
  { day: 2, focus: "Speaking", task: "Memorize Speaking Task 2 template. Say it out loud 10 times.", time: "15 min" },
  { day: 3, focus: "Writing", task: "Spelling drill: type all 10 words 5x each. Then write 1 email using template.", time: "20 min" },
  { day: 4, focus: "Speaking", task: "Memorize Task 3 & 4 templates. Practice 2 random prompts with timer.", time: "20 min" },
  { day: 5, focus: "Writing", task: "Write 2 Academic Discussion responses. Keep under 20 words per sentence.", time: "20 min" },
  { day: 6, focus: "Speaking", task: "Listen & Repeat: do all Level 1 + Level 2. Then 2 speaking prompts timed.", time: "20 min" },
  { day: 7, focus: "Rest", task: "Review what you've memorized. Light vocab flashcards only.", time: "10 min" },
  { day: 8, focus: "Speaking", task: "3 random Speaking T1 prompts. Record on phone. Listen back. Fix filler words.", time: "20 min" },
  { day: 9, focus: "Writing", task: "Spelling drill again + write 1 integrated essay using template (time: 20 min).", time: "25 min" },
  { day: 10, focus: "Reading", task: "1 full passage timed (17 min). Review wrong answers.", time: "25 min" },
  { day: 11, focus: "Speaking", task: "Listen & Repeat Level 3. Then 2 interview questions — speak for 40-50 sec each.", time: "20 min" },
  { day: 12, focus: "Writing", task: "Write 1 email + 1 discussion. Run sentence checker. Fix any 20+ word sentences.", time: "25 min" },
  { day: 13, focus: "Listening", task: "Watch 1 TED-Ed video (no subtitles). Write main points. Check with subtitles.", time: "20 min" },
  { day: 14, focus: "Rest", task: "Vocab flashcards. Mark hard/easy. Review hard ones 3x.", time: "10 min" },
  { day: 15, focus: "Speaking", task: "Full mock: do all 4 speaking tasks back-to-back with timer. Record everything.", time: "20 min" },
  { day: 16, focus: "Writing", task: "Full writing mock: 10 sentences + email (7 min) + discussion (10 min).", time: "30 min" },
  { day: 17, focus: "Reading", task: "2 full passages timed (35 min total). No going back.", time: "35 min" },
  { day: 18, focus: "Listening", task: "Practice test listening section. Note-take using T-chart + shortcuts.", time: "30 min" },
  { day: 19, focus: "Speaking", task: "3 Speaking T1 + 2 interview Qs. Focus: NO filler, clear transitions only.", time: "20 min" },
  { day: 20, focus: "Writing", task: "Spelling drill (must get 10/10 without thinking). Then 1 essay.", time: "20 min" },
  { day: 21, focus: "Rest", task: "Review weakest section only. Light practice.", time: "15 min" },
  { day: 22, focus: "Full Test", task: "Take ETS free practice test. Full simulation. Note your score.", time: "2 hrs" },
  { day: 23, focus: "Review", task: "Review practice test results. List top 3 mistakes per section.", time: "30 min" },
  { day: 24, focus: "Speaking", task: "Fix top 3 speaking mistakes. Drill 5 prompts with those fixes.", time: "20 min" },
  { day: 25, focus: "Writing", task: "Fix top 3 writing mistakes. Rewrite your weakest practice response.", time: "20 min" },
  { day: 26, focus: "Speaking", task: "Final drill: 5 random prompts. Must use template perfectly every time.", time: "20 min" },
  { day: 27, focus: "Writing", task: "Final drill: 1 email + 1 discussion. Zero spelling errors. Short sentences.", time: "20 min" },
  { day: 28, focus: "Full Test", task: "Second full practice test. Compare with Day 22 score.", time: "2 hrs" },
  { day: 29, focus: "Light Review", task: "Review templates one last time. Vocab hard words only.", time: "15 min" },
  { day: 30, focus: "Test Day", task: "You're ready. Get sleep. Arrive 30 min early. Passport. You got this. 🎯", time: "—" }
];
